### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by koyurion** [cmbi/hssp#121]
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Server Error: Service Unavailable for url: https://www.cmbi.umcn.nl/xssp/api/create/pdb_file/dssp/

Is something wrong?

**Comment by cbaakman** [comment]
Dear @koyurion, yes we have a problem. The server broke and we're currently fixing it. Unfortunately we can't get it back up before next week. Sorry for the inconvenience!

**Comment by koyurion** [comment]
Thank you so much!

**Comment by cbaakman** [comment]
The server is back up now.
