### ISSUE TITLE
I want to calculate the helix content, so which tool is much better? HSSP or DSSP?

### ISSUE THREAD

**Issue by AKBforever** [cmbi/hssp#123]
The download link in DSSP webpage of CMBI  directed me to HSSP project. It confused me. 
And  I installed the latest version DSSP 3.1.4; however, when I use gromacs gmx do_dssp command, it keeps telling me specifying dssp version. I realized I can only give integer number, so I try -ver 3. But the error still there. Can you please help me how to solve this problem?

**Comment by cbaakman** [comment]
Could you give the exact output from gromacs? DSSP 3.1.4 should work.

Also, you submitted this issue on the hssp repository, but did you download dssp from the dssp repository?
https://github.com/cmbi/dssp/releases/tag/3.1.4

(it has moved)

**Comment by AKBforever** [comment]
> Could you give the exact output from gromacs? DSSP 3.1.4 should work.
> 
> Also, you submitted this issue on the hssp repository, but did you download dssp from the dssp repository?
> https://github.com/cmbi/dssp/releases/tag/3.1.4
> 
> (it has moved)

Dear @cbaakman , thanks for your reply. Yes, I downloaded the DSSP 3.1.4 from the DSSP repository; but when I tried running DSSP, this error in the following snapshot occurred. I don't know how to solve this problem, the only way is to use the old version of DSSP?
![QQ图片20200711093743](https://user-images.githubusercontent.com/67896916/87213806-31e84500-c35a-11ea-9870-7bef06092a0e.png)

**Comment by cbaakman** [comment]
Have you tried to run the mkdssp executable itself and see if it had any outcome? I'd like to know what happens when you run the mkdssp executable on the pdb file that you were using in gromacs.

Also, you can tell gromacs which mkdssp executable to use. That's described here:
http://manual.gromacs.org/5.1/onlinehelp/gmx-do_dssp.html

**Comment by Yuanruikang** [comment]
the reason of your problem may be that you use a lower version of GMX. From my pratical situation,I installed dssp on  my Ubuntu 18.04 with GMX 2019.4 It run perfectly,but I have to export the path because dssp's name is mkdssp,not dssp in the path-/usr/local/bin/

**Comment by cbaakman** [comment]
Dear users,

this repository is discontinued. Please use:
[https://github.com/PDB-REDO/dssp](https://github.com/PDB-REDO/dssp)
