### ISSUE TITLE
Get HSSP Database 

### ISSUE THREAD

**Issue by BioinfTMU** [cmbi/hssp#124]
Hello. How can I download the HSSP database and store it?
I check
 rsync -avz rsync://rsync.cmbi.umcn.nl/hssp/ /local_hssp_path/
and 
ftp://ftp.cmbi.umcn.nl/pub/molbio/data/hssp/
but it doesn't work, and I can't download it.

**Comment by cbaakman** [comment]
```rsync -avz rsync://rsync.cmbi.umcn.nl/hssp/ /local_hssp_path/``` should work. It works in my case.

Doesn't it say "receiving incremental file list" ?

**Comment by BioinfTMU** [comment]
Yes. It says, but it doesn't download any HSSP file.

**Comment by cbaakman** [comment]
That means rsync is still busy listing all the files that are in the hssp databank folder. (120 000 files) Downloading individual hssp files is way faster. Try:

```
rsync -avz rsync://rsync.cmbi.umcn.nl/hssp/101m.hssp.bz2 .
``` 

Or replace 101m by the pdb accession code of the file you want.

**Comment by BioinfTMU** [comment]
Thank's a lot. It works correctly.
