### ISSUE TITLE
ChecksumError

### ISSUE THREAD

**Issue by t-nojiri** [cmbi/hssp#125]
I got a checksum error when building this OSS using spack.
This symptom occurred in all versions from 3.0.1 to 3.0.10.

Was the change intentional?
I just want to make sure it's not hacked.

**Comment by cbaakman** [comment]
We haven't changed anything to the hssp repository recently. Not to any version.

**Comment by cbaakman** [comment]
Also, I have no idea where this checksum comes from.

**Comment by t-nojiri** [comment]
thank you for your answer.

**Comment by adamjstewart** [comment]
I figured it out. The previous checksum came from https://github.com/cmbi/hssp/releases/download/3.0.10/xssp-3.0.10.tar.gz, not https://github.com/cmbi/hssp/archive/3.0.10.tar.gz. So I think it's safe to update all the checksums. Thanks for checking!

We can close this issue now.
