### ISSUE TITLE
A bug about hssp3.0.0

### ISSUE THREAD

**Issue by chase2555** [cmbi/hssp#128]
When I execute make mkdssp, I get an error, the error is as follows

g++ -g -O2 -o mkdssp src/dssp.o src/iocif.o src/mas.o src/mkdssp.o src/primitives-3d.o src/structure.o src/utils.o -lboost_date_time -lboost_filesystem - lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread src/mkdssp.o: in function 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const& boost::program_options::validators::get_single_string<char>( std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std:: char_traits<char>, std::allocator<char> > > > const&, bool)': /usr/include/boost/program_options/detail/value_semantic.hpp:58: response to 'boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char , std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' undefined citations /usr/include/boost/program_options/detail/value_semantic.hpp:62: response to 'boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char , std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' undefined citations src/mkdssp.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x20): undefined reference to 'boost::program_options'(validation_error::what) src / mkdssp.o :( data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE [_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE] + 0x20):. undefined references to 'boost :: program_options :: validation_error

**Comment by cbaakman** [comment]
Dear user,

this repository is no longer updated. The most recent updates are in:

https://github.com/PDB-REDO/dssp
