### ISSUE TITLE
Cannot make container from Dockerfile or singularity.sif

### ISSUE THREAD

**Issue by ceziegler** [cmbi/hssp#129]
Dockerfile gives the following error after Step 15/15 : RUN /app/autogen.sh && /app/configure && make

/bin/bash: /app/autogen.sh: /bin/sh^M: bad interpreter: No such file or directory
The command '/bin/bash -c /app/autogen.sh && /app/configure && make' returned a non-zero code: 126

And singularity fails when storing signatures:
ERROR  : Failed to set process capabilities
FATAL:   While performing build: while running engine: exit status 1

**Comment by cbaakman** [comment]
In the github repository, autogen.sh has unix line endings. Your version seems to have dos line endings. So your OS must have edited this file locally.

**Comment by ceziegler** [comment]
Used dos2unix to fix line endings in Dockerfile and built docker container successfully. Bedankt voor de hulp!
