### ISSUE TITLE
make error for linux @  cbaakman

### ISSUE THREAD

**Issue by K-kiran90** [cmbi/hssp#132]
error: #warning is a GCC extension [-Werror]
   23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      |      ^~~~~~~
/home/kiran/Downloads/boost_1_81_0/boost/include/boost/math/tools/config.hpp:23:6: error: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Werror=cpp]

**Comment by K-kiran90** [comment]
base) kiran@kiran-B360M-DS3H:~/Downloads/hssp-3.1.5$ make
make  all-am
make[1]: Entering directory '/home/kiran/Downloads/hssp-3.1.5'
depbase=`echo src/fasta.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
g++ -DHAVE_CONFIG_H -I.  -std=c++11 -pedantic -Wall -Werror -Wno-reorder -pthread -I/home/kiran/Downloads/boost_1_81_0/boost/include   -I./src/   -g -O2 -MT src/fasta.o -MD -MP -MF $depbase.Tpo -c -o src/fasta.o src/fasta.cpp &&\
mv -f $depbase.Tpo $depbase.Po
In file included from /home/kiran/Downloads/boost_1_81_0/boost/include/boost/math/quaternion.hpp:14,
                 from src/primitives-3d.h:16,
                 from src/structure.h:11,
                 from src/fasta.cpp:2:
/home/kiran/Downloads/boost_1_81_0/boost/include/boost/math/tools/config.hpp:23:6: error: #warning is a GCC extension [-Werror]
   23 | #    warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)"
      |      ^~~~~~~
/home/kiran/Downloads/boost_1_81_0/boost/include/boost/math/tools/config.hpp:23:6: error: #warning "The minimum language standard to use Boost.Math will be C++14 starting in July 2023 (Boost 1.82 release)" [-Werror=cpp]
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:661: src/fasta.o] Error 1
make[1]: Leaving directory '/home/kiran/Downloads/hssp-3.1.5'
make: *** [Makefile:472: all] Error 2

**Comment by K-kiran90** [comment]
@cbaakman Can you help me to figure out ASAP

**Comment by K-kiran90** [comment]
Also unable to get latest windows version of DSSP

**Comment by cbaakman** [comment]
It seems that boost wants you to use c++14 language standard, but the version used is c++11. I'm not sure why your configuration chooses that standard. Upgrading gcc might help.

For the latest version of DSSP, check here:
https://github.com/PDB-REDO/dssp

**Comment by K-kiran90** [comment]
Can you please share me the windows DSSP4 version i.e., DSSP4.exe file

I found many errors when I installed the following link you shared with me.

**Comment by cbaakman** [comment]
I don't have the DSSP4 exe for windows, sorry. I think you should discuss this with the maintainers of DSSP4.

**Comment by maxy0617** [comment]
Hi! 

I met the same error when installing dssp and boost, and I solved it in this way:
This error is due to the unmatching version of C++, as the version for boost should be c++14, but in the makefile of dssp, the default is c++11.
First, you should check the c++ version in your own system, by print __cplusplus. The more detail can be accessed easily in search engine.
After checking that you got c++14 in your system, you can change the config in Makefile in the directory of hssp: 
Replace '-std=c++11' as '-std=c++14'.
Then you can use the command make to install.

Hope this is helpful!
